from setuptools import find_packages, setup

setup(
    name="capybara",
    version="0.1.1",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.115.6",
        "grpcio>=1.59.3",
        "httpx>=0.27",
        "Jinja2>=3.1.2",
        "litellm>=1.55.7",
        "llama_index>=0.12.7",
        "llama_parse>=0.5.18",
        "numpy>=2.2.0",
        "ollama>=0.4.4",
        "openai>=1.58.1",
        "orjson>=3.10.12",
        "peewee>=3.17.5",
        "pgvector>=0.3.0",
        "Pillow>=11.0.0",
        "protobuf>=5.29.2",
        "pyarrow>=14.0.1",
        "pydantic>=2.10.4",
        "pypinyin>=0.53.0",
        "python-dotenv>=1.0.1",
        "python_docx>=1.1.0",
        "redis>=5.0.0",
        "Requests>=2.32.3",
        "sentence_transformers>=2.2.2",
        "uvicorn>=0.34.0",
    ],
    author="Yue Wu",
    author_email="your.email@example.com",
    description="A short description of your capybara project",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/mathwuyue/capybara",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.10",
)
